version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin-ksp:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "com.google.devtools.ksp"
          - "androidx.compose.compiler:compiler"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[BOT][Dependencies]"
    labels:
      - "dependabot"
      - "dependencies"
    reviewers:
      - "AdiJr"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[BOT][Github Actions]"
    labels:
      - "dependabot"
      - "github-actions"
    reviewers:
      - "AdiJr"
