object Versions {
    const val accompanistVersion = "0.17.0"
    const val coroutinesVersion = "1.5.0"
    const val materialVersion = "1.8.0"
    const val appcompatVersion = "1.3.0"
    const val activityComposeVersion = "1.6.1"
    const val composeNavigationVersion = "2.5.3"
    const val composeUIVersion = "1.3.3"
    const val lifecycleVersion = "2.6.0"
    const val composeRuntimeLivedataVersion = "1.3.3"
    const val composeToolingVersion = "1.3.3"
    const val composeMaterialVersion = "1.3.1"
    const val composeViewmodelVersion = "2.5.1"
    const val liveDataVersion = "2.6.0"
    const val testVersion = "1.3.0"
    const val jUnitKtxVersion = "1.1.2"
    const val espressoCoreVesion = "3.2.0"
    const val hiltVersion = "2.45"
    const val hiltNavigationComposeVersion = "1.0.0-alpha03"
    const val jUnitVersion = "4.13"
    const val coilVersion = "1.3.0"
    const val lottieVersion = "4.0.0"
    const val retrofitVersion = "2.9.0"
    const val okhttpLoggingVersion = "4.9.1"
    const val timberVersion = "5.0.0"
}
