name: Pull Request Checks

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - development
      - master

jobs:
  tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup-env-action

      - name: Run Tests
        run: ./gradlew clean testStageDebugUnitTest

  lint:
    name: "Run Linter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup-env-action

      - name: Run Linter
        run: ./gradlew clean lintStageDebug

  detekt:
    name: "Run Detekt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup-env-action

      - name: Run Detekt
        run: ./gradlew clean detektStageDebug

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: Detekt Report
          path: app/build/reports/detekt.html
          if-no-files-found: ignore

  mobsfscan:
    name: "MobSF Security Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: MobSF Scan
        uses: MobSF/mobsfscan@3d87bc570c4614d705547bddb521395663dba353 #v0.4.5
        with:
          args: '. --html --type android --version --output results.html || true'

      - name: Archive MobSF report
        uses: actions/upload-artifact@v4
        with:
          name: MobSF scan report
          path: results.html
          if-no-files-found: error
